FROM golang:1.17 AS build

WORKDIR ../../
COPY go.mod .
COPY go.sum .
RUN go mod download

COPY . .

ENV CGO_ENABLED=1
RUN GOOS=linux GOARCH=amd64 go build -o /bin/applico-api ./cmd/applico-api/main.go

FROM alpine:3.13.6 AS runtime

WORKDIR /

COPY --from=build /bin/applico-api applico-api

ENTRYPOINT ["./applico-api"]